source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'mongo'
gem "mongoid", "~> 2.4"
gem "bson_ext", "~> 1.5"

gem 'jquery-rails'
gem 'haml', '~> 3.1.4'
gem "simple_form", "1.5.2"
gem "settingslogic", "2.0.6"
gem 'awesome_nested_fields', '0.5.3'

group :assets do
  gem 'compass-rails'
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test do
  gem 'turn', '0.8.2', :require => false
end
